### ISSUE TITLE
Question: multiple projects on one board

### ISSUE THREAD

**Issue by sirkitree** [mglaman/contribkanban.com#68]
Is it possible to show multiple projects on one board?

**Comment by mglaman** [comment]
Currently, it is only possible via a tag - like https://contribkanban.com/sprint/d8Media. Which I just realized is no longer showing the project's name :(. Those boards also are not (yet) configurable like [regular project boards](https://github.com/mglaman/contribkanban.com/blob/master/config/boards/sample.json)

Were you thinking of taking the idea of the current sprint boards and instead having it aggregate two project queues instead of by tag? It could be done. The main reason I haven't is that the RestWS module does not support AND/OR queries, so it's a query for every option.

**Comment by sirkitree** [comment]
I think that using a tag will serve my purpose. The request comes from a feature of waffle.io which allows you to have all of the issues from multiple projects showing up on one board. In my case we have a module and a theme that are very tied together and so tracking work on both of them on one board would be ideal, but utilizing tags will get us very close.

**Comment by mglaman** [comment]
Ah is this for the AMPd projects? If you want to start by tagging things with "AMP", then go to "https://contribkanban.com/browse/sprint" and type "AMP" into the tag input, click add.

In the meantime, I'll try to whittle away some time to make this work. It shouldn't be *too hard* technically. It's just adjusting the internal JSON and how I call the API

**Comment by sirkitree** [comment]
Ok, no huge deal, we've only got about another three weeks to go so you shouldn't make something like this a high priority on our account :wink:

**Comment by mglaman** [comment]
;) Sounds good. I'll probably give it a shot soon, though. I've toyed with this idea for the Drupal Commerce ecosystem, things that group like modules that make sense to sprint on at once, without needing to tag every stinkin' issue.

**Comment by mglaman** [comment]
OR queries have been figured out! Let's see about making a custom board for just AMP and bringing in each project ;)

**Comment by mglaman** [comment]
@sirkitree this is super late, but https://contribkanban.com/custom/amp.

Not discovered via the UI yet. But this combines the two projects. See https://github.com/mglaman/contribkanban.com/blob/master/config/boards/custom/amp.json
